### ISSUE TITLE
Bootstrap-multiselect webjar needs license file included.

### ISSUE THREAD

**Issue by JoanMMills** [webjars/bootstrap-multiselect#8]
The webjar for version 0.9.13 does not include the license file. As per the license "Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer."

**Comment by jamesward** [comment]
Most of the Classic WebJars do not include the actual `LICENSE` file because the metadata specifies the license.  I think that sufficiently achieves the goals of the license.  But I've included it anyway and I'm publishing `0.9.13-1` with the change.
